# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "MathLib",
    srcs = glob(["**/*.cc"]),
    hdrs = glob(["**/*.h"]),
    visibility = ["//visibility:public"],
)