# https://docs.bazel.build/versions/master/be/c-cpp.html#cpp_binary
cpp_binary(
    name = "Aplication",
    srcs = ["Aplication.cpp"],
    deps = ["//src/lib:MathLib"],
)

cpp_binary(
    name = "pointer_example_main",
    srcs = ["pointer_example_main.cpp"],
    deps = ["//src/lib:MathLib"],
)